### ISSUE TITLE
error rendering View in jetty maven plugin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [voodoodyne/htmleasy#1]
```
What steps will reproduce the problem?
i created the following class

@Path("/")
@Service
public class ViewCloudController {

    @GET
    @Path("/")
    public View viewCloud() {
        return new View("/WEB-INF/jsp/public.jsp");
    }



What is the expected output? What do you see instead?
instead of displaying the jsp i get the following stack trace:

Dec 17, 2009 2:00:51 AM org.jboss.resteasy.core.SynchronousDispatcher 
handleFailure
SEVERE: Failed executing GET 
org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find 
MessageBodyWriter 
for response object of type: com.googlecode.htmleasy.View of media type: 
application/xml
    at org.jboss.resteasy.core.ServerResponse.writeTo(ServerResponse.java:167)
    at 
org.jboss.resteasy.core.SynchronousDispatcher.writeJaxrsResponse(SynchronousDisp
atcher.java:
403)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:340)
    at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:103)
    at 
org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServ
letDispatcher.java
:114)
    at 
org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServ
letDispatcher.java
:70)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at com.googlecode.htmleasy.ResteasyFilter.doFilter(ResteasyFilter.java:375)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1148)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:387)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:417)
    at 
org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollecti
on.java:230)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:324)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:535)
    at 
org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.ja
va:865)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:539)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:520)

i believe it is configured correctly as i can call normal rest methods.

What version of the product are you using? On what operating system?
htmleasy 0.6, resteasy 1.2.1GA, spring 2.5.6.SEC01, Mac osx snow leopard

Please provide any additional information below.
here is the jetty config in my pom.xml:

<plugins>
            <plugin>
                <groupId>org.mortbay.jetty</groupId>
                <artifactId>maven-jetty-plugin</artifactId>
                <version>6.1.16</version>
                <configuration>
                    <scanIntervalSeconds>10</scanIntervalSeconds>
                    <connectors>
                        <connector implementation="org.mortbay.jetty.nio.SelectChannelConnector">
                            <port>8080</port>
                            <maxIdleTime>60000</maxIdleTime>
                        </connector>
                    </connectors>
                    <contextPath>/</contextPath>
                </configuration>
            </plugin>

```

Original issue reported on code.google.com by `yestech....@gmail.com` on 17 Dec 2009 at 10:03

**Comment by mthilinas** [comment]
I got like error plese help me..
